//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOV_UNIDADES_TRASLADOS
    {
        public string ID_UNIDAD_TRASLADO { get; set; }
        public string PROYECTO_FUNCIONARIO_ID { get; set; }
    
        public virtual PROYECTO_FUNCIONARIO PROYECTO_FUNCIONARIO { get; set; }
    }
}
