//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO_FUNCIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO_FUNCIONARIO()
        {
            this.NOV_UNIDADES_TRASLADOS = new HashSet<NOV_UNIDADES_TRASLADOS>();
        }
    
        public string PROYECTO_FUNCIONARIO_ID { get; set; }
        public string PROYECTO_NOVEDAD_ID { get; set; }
        public string FUNCIONARIO_NOVEDAD_ID { get; set; }
        public int ID_CLASE_NOVEDAD { get; set; }
    
        public virtual FUNCIONARIO_NOVEDAD FUNCIONARIO_NOVEDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOV_UNIDADES_TRASLADOS> NOV_UNIDADES_TRASLADOS { get; set; }
        public virtual PROYECTO_NOVEDAD PROYECTO_NOVEDAD { get; set; }
        public virtual PROYECTO_FUNCIONARIO PROYECTO_FUNCIONARIO1 { get; set; }
        public virtual PROYECTO_FUNCIONARIO PROYECTO_FUNCIONARIO2 { get; set; }
    }
}
